#!/usr/bin/env python3
"""Build nkv (dense hash, binary index) databases from JSON key/value
files.

Usage: python3 build_db3.py input.json output.nkv [--check]

Sharded mode (optional; see nkv.nix): one nkv file per shard slice of
the key hash h = sha256(key) hex, slice h[24:24+d] (d = 1/2/3 -> 16/256/
4096 shards; disjoint from the probe-seed slice 56..64):

  python3 build_db3.py input.json --shards 256 --prefix dir/ [--check]

Every shard is written (empty shards are valid nkv files with N = 0,
M = 16), so the Nix wrapper always resolves a key to an existing file;
only the needed shard is read per lookup.

# nkv layout (all offsets absolute, chars == bytes):
#   0..3     magic "NKV3"
#   4..6     N         (3 base-255 bytes)
#   7..10    M         (4 base-255 bytes)
#   11       koffW     (1 base-255 byte: 1..4)
#   12       klenW     (1 base-255 byte: 1..3)
#   13       vlenW     (1 base-255 byte: 1..3)
#   14..     M entries of EW bytes, EW = koffW + klenW + vlenW (3..10),
#            fields at entry offsets:
#            keyOff @0 (koffW) | keyLen @koffW (klenW)
#            | valLen @koffW+klenW (vlenW)
#            (unused slot: EW bytes of 0x01; keyOff = 0 marks an unused
#            slot — a real keyOff is always >= 14 + EW*M > 0)
#   then     data region: for each key in JSON insertion order, the key's
#            UTF-8 bytes immediately followed by the value's UTF-8 bytes.
#            keyOff is absolute from the file start; the value offset is
#            keyOff + keyLen (implicit, not stored).
#
# The base-255 decode table (255 bytes 0x01..0xFF -> digit 0..254) is a
# format constant shared by every nkv file; it is NOT carried in the
# database files. The static Nix module `nkv-table.nix` holds it as a
# 255-entry attrset and is generated by
#   python3 build_db3.py --write-table nkv-table.nix
# (nkv.nix imports it; it costs nothing per lookup).

Hashing: h = sha256(key) in lowercase hex. Initial slot
s0 = int(h[56:64], 16)
AND (M-1); linear probing, first empty slot wins. M = next_pow2(max(16,
# There are no fingerprints: every occupied slot is read and confirmed by a
# byte-for-byte key comparison, and a walk ends at a key match or an unused
# slot (keyOff = 0).

Field encoding ("base-255"): each byte of a field is one digit plus one
(digit in 0..253 -> byte in 1..254, big-endian digits), so every byte in
the whole file is in 0x01..0xFF and the file never contains NUL (the one
nkv.nix decodes a field byte via the static
nkv-table.nix attrset (byte 1-char string -> digit), imported once per
eval (import cache); the table is a format constant, not file data.

Limits (builder-enforced): N and per-key/value lengths
< 254^3 (widths capped at 3 bytes); M and keyOff < 254^4 (widths
capped at 4 bytes); no key or value may contain a NUL byte. Entry field
widths (koffW, klenW, vlenW) are the minimum that fit the table's
maximum key offset / key length / value length, stored once in the
header.

JSON input: an object; duplicate keys keep the last (dict semantics,
matching fromJSON). Keys must be strings; values are arbitrary JSON:
string values are stored raw (nkv.nix get/getOr return them as-is),
non-string values are stored as compact JSON documents, so
nkv.nix getJson/getOrJson decode them back with builtins.fromJSON.
"""
import argparse
import hashlib
import json
import os
import sys

MAGIC = b"NKV3"
H = 14
T0 = H                                # index region start (table is static)
FO = 4                               # M / keyOff field width (base-255)
FL = 3                               # N / key|value len field width
B = 254
MAX_FIELD3 = B ** FL - 1             # 16,387,063
MAX_FIELD4 = B ** FO - 1             # 4,162,314,255

# entry layout: keyOff @0 (koffW) | keyLen @koffW (klenW)
#   | valLen @koffW+klenW (vlenW)
#   (keyOff = 0 marks an unused slot)
#   entry width EW = koffW + klenW + vlenW (3..10), widths in header


def enc(v, digits):
    """Encode v as `digits` base-255 bytes (big-endian digits, byte = d+1)."""
    if v < 0 or v >= B ** digits:
        raise ValueError(f"value {v} out of range for {digits} base-255 bytes")
    out = bytearray()
    for i in range(digits - 1, -1, -1):
        d = (v // B ** i) % B
        out.append(d + 1)
    return bytes(out)


def dec(b, digits):
    """Inverse of enc."""
    v = 0
    for x in b[:digits]:
        v = v * B + (x - 1)
    return v


def next_pow2(v):
    p = 1
    while p < v:
        p *= 2
    return p


def width_for(v, maxw, what):
    """Smallest base-255 byte width (1..maxw) that holds v; raise if none."""
    w = 1
    while v > B ** w - 1:
        w += 1
        if w > maxw:
            raise ValueError(f"{what} {v} needs more than {maxw} base-255 bytes")
    return w


def seed_of(kb):
    """Probe seed: int(h[56:64], 16) for h = sha256(key) hex."""
    return int(hashlib.sha256(kb).hexdigest()[56:64], 16)


def norm_value(v):
    """Value -> stored bytes: strings raw; anything else compact JSON.

    ensure_ascii (the default) keeps the encoding pure ASCII — no NUL,
    no high bytes — so it is always file-safe; builtins.fromJSON
    round-trips it exactly.
    """
    if isinstance(v, str):
        return v.encode("utf-8")
    return json.dumps(v, separators=(",", ":")).encode("ascii")

def build(pairs):
    """pairs: iterable of (str key, str value) pairs. Returns file bytes."""
    items = list(pairs)
    n = len(items)
    m = next_pow2(max(16, -(-5 * n // 4)))   # ceil(1.25 n), load <= 0.8
    if n > MAX_FIELD3:
        raise ValueError("too many entries")
    if m > MAX_FIELD4:
        raise ValueError("table too large")
    kb_list = []
    vb_list = []
    for k, v in items:
        kb, vb = k.encode("utf-8"), norm_value(v)
        if 0 in kb or 0 in vb:
            raise ValueError("key or value contains NUL")
        kb_list.append(kb)
        vb_list.append(vb)
    # data region: interleaved (key, value, key, value, ...); a value
    # immediately follows its key, so only keyOff is stored per entry
    data_region = b"".join(kb + vb for kb, vb in zip(kb_list, vb_list))

    # open addressing, first empty slot (identical to the Nix side)
    slot_of = {}
    used = set()
    for i, kb in enumerate(kb_list):
        s0 = seed_of(kb) & (m - 1)
        s = s0
        while s in used:
            s = (s + 1) & (m - 1)
        slot_of[i] = s
        used.add(s)

    # Field widths: the smallest per-field byte widths that fit this
    # table's maxima, stored once in the header.
    max_klen = max(map(len, kb_list)) if kb_list else 0
    max_vlen = max(map(len, vb_list)) if vb_list else 0
    klenW = width_for(max_klen, FL, "key length")
    vlenW = width_for(max_vlen, FL, "value length")
    # The keyOff width depends on the entry width (the data region starts
    # after the index region), so iterate to a fixpoint: monotone, so it
    # converges in at most FO rounds.
    data_len = len(data_region)
    last_kv = (len(kb_list[-1]) + len(vb_list[-1])) if kb_list else 0
    koffW = 1
    for _ in range(FO):
        ew = koffW + klenW + vlenW
        max_koff = T0 + ew * m + data_len - last_kv
        need = width_for(max_koff, FO, "key offset")
        if need <= koffW:
            break
        koffW = need
    ew = koffW + klenW + vlenW

    header = (
        MAGIC
        + enc(n, FL)
        + enc(m, FO)
        + bytes([koffW + 1, klenW + 1, vlenW + 1])
    )
    assert len(header) == H

    o_koff = 0
    o_klen = koffW
    o_vlen = koffW + klenW
    idx = bytearray(b"\x01" * (ew * m))   # base-255 zero = unused slot
    # NOTE: e below is buffer-relative (idx starts at file offset T0).
    ko = T0 + ew * m
    for i in range(n):
        kb, vb = kb_list[i], vb_list[i]
        e = ew * slot_of[i]
        assert e + ew <= len(idx)
        idx[e + o_koff:e + o_koff + koffW] = enc(ko, koffW)
        idx[e + o_klen:e + o_klen + klenW] = enc(len(kb), klenW)
        idx[e + o_vlen:e + o_vlen + vlenW] = enc(len(vb), vlenW)
        ko += len(kb) + len(vb)

    blob = header + bytes(idx) + data_region
    if len(blob) > MAX_FIELD4:
        raise ValueError("file too large for 4-byte base-255 offsets")
    return blob

def header_widths(data):
    """(koffW, klenW, vlenW) from the header, validated."""
    koffW = data[11] - 1
    klenW = data[12] - 1
    vlenW = data[13] - 1
    if not (1 <= koffW <= FO and 1 <= klenW <= FL
            and 1 <= vlenW <= FL):
        raise ValueError(
            f"bad field widths: koffW={koffW} klenW={klenW} vlenW={vlenW}"
        )
    return koffW, klenW, vlenW



def parse(path):
    """Independent parser: (n, m, [(key, value)]) decoded from the file."""
    data = open(path, "rb").read()
    if data[:4] != MAGIC:
        raise ValueError(f"bad magic: {data[:4]!r}")
    n = dec(data[4:7], FL)
    m = dec(data[7:11], FO)
    if m < n:
        raise ValueError(f"table size {m} < entry count {n}")
    koffW, klenW, vlenW = header_widths(data)
    if 0 in data:
        raise ValueError("file contains NUL (invalid for Nix readFile)")
    ew = koffW + klenW + vlenW
    o_koff, o_klen, o_vlen = 0, koffW, koffW + klenW
    out = []
    for s in range(m):
        e = T0 + ew * s
        if dec(data[e:e + koffW], koffW) == 0:
            continue  # keyOff = 0 marks an unused slot
        koff = dec(data[e:e + koffW], koffW)
        klen = dec(data[e + o_klen:e + o_klen + klenW], klenW)
        vlen = dec(data[e + o_vlen:e + o_vlen + vlenW], vlenW)
        out.append(
            (
                data[koff:koff + klen].decode("utf-8"),
                data[koff + klen:koff + klen + vlen].decode("utf-8"),
            )
        )
    if len(out) != n:
        raise ValueError(f"decoded {len(out)} entries, header says {n}")
    return n, m, out


def entry_geometry(data):
    """(ew, koffW, klenW, vlenW, o_koff, o_klen, o_vlen) from header."""
    koffW, klenW, vlenW = header_widths(data)
    ew = koffW + klenW + vlenW
    o_koff, o_klen, o_vlen = 0, koffW, koffW + klenW
    return ew, koffW, klenW, vlenW, o_koff, o_klen, o_vlen


def python_get_data(data, key):
    """Open-addressing probe over in-memory file bytes — independent of
    the Nix implementation."""
    m = dec(data[7:11], FO)
    ew, koffW, klenW, vlenW, o_koff, o_klen, o_vlen = entry_geometry(data)
    kb = key.encode("utf-8")
    s0 = seed_of(kb) & (m - 1)
    for i in range(m):
        s = (s0 + i) & (m - 1)
        e = T0 + ew * s
        koff = dec(data[e + o_koff:e + o_koff + koffW], koffW)
        if koff == 0:
            return None  # keyOff = 0 marks an unused slot
        klen = dec(data[e + o_klen:e + o_klen + klenW], klenW)
        if data[koff:koff + klen] == kb:
            vlen = dec(data[e + o_vlen:e + o_vlen + vlenW], vlenW)
            return data[koff + klen:koff + klen + vlen].decode("utf-8")
    return None


def python_get(path, key):
    """Probe over raw bytes."""
    return python_get_data(open(path, "rb").read(), key)


def shard_slice(key, digits):
    """Shard slice of sha256(key): hex chars [24:24+digits] — disjoint from
    the probe-seed slice h[56:64] used by nkv.nix."""
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[24:24 + digits]


def shard_names(digits):
    """All 16**digits shard slice names, e.g. ['00', '01', ..., 'ff']."""
    return [format(i, "0%dx" % digits) for i in range(16 ** digits)]


TABLE_HEADER = """# nkv decode table (static, format constant).
#
# attrset mapping every 1-byte string (bytes 0x01..0xFF) to its digit
# value (byte - 1). nkv database files store field digits as raw bytes
# and nkv.nix decodes each byte through this table, so the table is a
# format constant shared by every nkv database: it is NOT part of any
# database file. Generated by
#   python3 build_db3.py --write-table nkv-table.nix
# and imported once per eval by nkv.nix (Nix import cache).
#
# The file intentionally contains raw (non-UTF-8) bytes: Nix accepts them
# in string literals, and escaping is only used for the four bytes that
# would break the literal (0x0A -> \\n, 0x0D -> \\r, 0x22 -> \\", 0x5C
# -> \\\\). Do not hand-edit.
"""


def gen_table_nix():
    """The 255-entry decode table as Nix source (latin-1 bytes)."""
    entries = []
    for v in range(255):
        b = v + 1
        if b == 0x0A:
            k = "\\n"
        elif b == 0x0D:
            k = "\\r"
        elif b == 0x22:
            k = '\\"'
        elif b == 0x5C:
            k = "\\\\"
        else:
            k = chr(b)
        entries.append('  "%s" = %d;' % (k, v))
    return (TABLE_HEADER + "{\n" + "\n".join(entries) + "\n}\n").encode("latin-1")


def build_sharded(pairs, digits, prefix):
    """Write one nkv file per shard slice into prefix/. Every shard is
    written (empty ones are valid nkv files: N = 0, M = 16), so the
    Nix wrapper never needs a missing-file branch. Returns
    {slice: (n, m, size)} over all shards."""
    os.makedirs(prefix, exist_ok=True)
    groups = {}
    for k, v in pairs.items():
        groups.setdefault(shard_slice(k, digits), []).append((k, v))
    stats = {}
    for s in shard_names(digits):
        blob = build(groups.get(s, []))
        with open(os.path.join(prefix, s + ".nkv"), "wb") as f:
            f.write(blob)
        stats[s] = (dec(blob[4:7], FL), dec(blob[7:11], FO), len(blob))
    return stats


def check_sharded(pairs, digits, prefix):
    """Sharded --check: parse every shard file independently, then probe
    each key with the Python probe implementation in its own shard."""
    blobs = {}
    total = 0
    for s in shard_names(digits):
        path = os.path.join(prefix, s + ".nkv")
        n, m, entries = parse(path)
        if len({k for k, _ in entries}) != n:
            sys.exit(f"check: duplicate keys in {s}.nkv")
        total += n
        blobs[s] = open(path, "rb").read()
    if total != len(pairs):
        sys.exit(f"check: shard entry total {total} != input {len(pairs)}")
    bad = 0
    for k, v in pairs.items():
        s = shard_slice(k, digits)
        want = norm_value(v).decode("utf-8")
        got = python_get_data(blobs[s], k)
        if got != want:
            bad += 1
            if bad <= 5:
                print(f"MISMATCH {k!r} [{s}]: want {want!r} got {got!r}",
                      file=sys.stderr)
    miss = "\x01\x02__definitely_missing__"
    if python_get_data(blobs[shard_slice(miss, digits)], miss) is not None:
        print("check: unexpected hit for absent key", file=sys.stderr)
        bad += 1
    if bad:
        print(f"check: {len(pairs) - bad}/{len(pairs)} ok  FAIL")
        sys.exit(1)
    print(f"check: {len(pairs)}/{len(pairs)} ok across "
          f"{16 ** digits} shards (miss -> None)")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", nargs="?",
                    help="input JSON object (omit with --write-table)")
    ap.add_argument("output", nargs="?",
                    help="output file (single-file mode); omit with --shards")
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify every key with an independent probe",
    )
    ap.add_argument(
        "--shards", type=int, default=0,
        help="sharded mode: 16, 256 or 4096 files (see --prefix)",
    )
    ap.add_argument("--prefix", default=None,
                    help="output directory for sharded mode")
    ap.add_argument("--write-table", metavar="FILE", default=None,
                    help="write the static decode table (nkv-table.nix) "
                         "to FILE and exit")
    args = ap.parse_args()

    if args.write_table:
        with open(args.write_table, "wb") as f:
            f.write(gen_table_nix())
        print(f"wrote {args.write_table}: decode table (255 entries)")
        return

    if not args.input:
        ap.error("input JSON object required (or --write-table)")

    with open(args.input) as f:
        pairs = json.load(f)
    if not isinstance(pairs, dict):
        sys.exit("input must be a JSON object")
    for k in pairs:
        if not isinstance(k, str):
            sys.exit(f"non-string key: {k!r}")

    if args.shards:
        digits = {16: 1, 256: 2, 4096: 3}.get(args.shards)
        if digits is None:
            sys.exit("--shards must be 16, 256 or 4096")
        if args.output:
            sys.exit("--shards mode: omit the output file (use --prefix)")
        if not args.prefix:
            sys.exit("--shards requires --prefix <dir>")
        stats = build_sharded(pairs, digits, args.prefix)
        ns = [s[0] for s in stats.values() if s[0]]
        sizes = [s[2] for s in stats.values()]
        print(
            f"wrote {len(stats)} shards in {args.prefix}/: "
            f"{len(pairs)} entries, keys/shard "
            f"{min(ns) if ns else 0}..{max(ns) if ns else 0}, "
            f"file {min(sizes)}..{max(sizes)} bytes"
        )
        if args.check:
            check_sharded(pairs, digits, args.prefix)
        return

    if not args.output:
        sys.exit("output file required (or use --shards --prefix)")
    if args.prefix:
        sys.exit("--prefix requires --shards")

    data = build(list(pairs.items()))
    with open(args.output, "wb") as f:
        f.write(data)
    n, m = dec(data[4:7], FL), dec(data[7:11], FO)
    koffW, klenW, vlenW = header_widths(data)
    print(
        f"wrote {args.output}: {len(data)} bytes, {n} entries, "
        f"M={m} load={n / m:.3f}, "
        f"widths off={koffW} klen={klenW} vlen={vlenW} "
        f"(EW={koffW + klenW + vlenW})"
    )

    if args.check:
        n2, m2, entries = parse(args.output)
        if (n2, m2) != (n, m):
            sys.exit(f"check: header mismatch {(n2, m2)} != {(n, m)}")
        if len({k for k, _ in entries}) != n:
            sys.exit("check: duplicate keys in decoded file")
        bad = 0
        blob = open(args.output, "rb").read()
        for k, v in pairs.items():
            want = norm_value(v).decode("utf-8")
            got = python_get_data(blob, k)
            if got != want:
                bad += 1
                if bad <= 5:
                    print(
                        f"MISMATCH {k!r}: want {want!r} got {got!r}",
                        file=sys.stderr,
                    )
        miss = "\x01\x02__definitely_missing__"
        if python_get_data(blob, miss) is not None:
            print("check: unexpected hit for absent key", file=sys.stderr)
            bad += 1
        if bad:
            print(f"check: {len(pairs) - bad}/{len(pairs)} ok  FAIL")
            sys.exit(1)
        print(f"check: {len(pairs)}/{len(pairs)} ok (miss -> None)")


if __name__ == "__main__":
    main()