#!/usr/bin/env python3
"""Emit kv_bin.nix (NKB v1 lookup) with the b2 byte-pair table inlined.

kv_bin.nix is plain, self-contained Nix using only builtins.readFile and
builtins.substring. The only generated part is the 255-entry b2 table
(two chars of the 32-char alphabet -> one base-255 digit).

Run: python3 gen_kv_bin.py   (writes ./kv_bin.nix)
"""

ALPH = "abcdefghijklmnopqrstuvwxyz234567"


def b2_table():
    lines = []
    for hi in range(32):
        for lo in range(32):
            if (hi, lo) == (31, 31):  # digit 255 is never emitted
                continue
            lines.append(f'    "{ALPH[hi]}{ALPH[lo]}" = {hi * 32 + lo};')
    return "\n".join(lines)


TEMPLATE = """# NKB v1 — fast static key/value lookup over a precomputed file, using only
# builtins.readFile and builtins.substring (plus integer math and the
# bytewise string comparison operator <).
#
# Lookup is a binary search over a bytewise-sorted key table; no hashing.
# See README.md and REPORT.md for the format and benchmarks.
#
# Generated by gen_kv_bin.py (inlines the b2 table); the rest is plain Nix.

let
  H = 64;   # header width (chars == bytes)
  W = 24;   # index entry width

  # b2: two chars of the 32-char alphabet -> one base-255 digit (hi*32+lo).
  # Digit 255 (pair "77") is unused: encoded values are < 255^digits.
  b2 = {
__B2__
  };

  pair = s: i: b2."${builtins.substring i 2 s}";

  # 4 chars -> value < 255^2 (lengths)
  dec2 = s: pair s 0 + 255 * (pair s 2);

  # 8 chars -> value < 255^4 (offsets, counts)
  dec4 = s:
    let
      p0 = pair s 0;
      p1 = pair s 2;
      p2 = pair s 4;
      p3 = pair s 6;
    in p0 + 255 * (p1 + 255 * (p2 + 255 * p3));
in
db:
  let
    raw = builtins.readFile db;

    # Entry layout (24 chars): off_k 8 | len_k 4 | off_v 8 | len_v 4.
    # Offsets are absolute from the start of the file.
    n = dec4 (builtins.substring 4 8 raw);

    keyAt = i:
      let
        e = H + W * i;
        off = dec4 (builtins.substring e 8 raw);
        len = dec2 (builtins.substring (e + 8) 4 raw);
      in builtins.substring off len raw;

    valueAt = i:
      let
        e = H + W * i;
        off = dec4 (builtins.substring (e + 12) 8 raw);
        len = dec2 (builtins.substring (e + 20) 4 raw);
      in builtins.substring off len raw;

    # Binary search: keys are strictly ascending in byte order.
    search = key: lo: hi:
      if lo >= hi then null
      else
        let
          m = (lo + hi) / 2;   # integer division truncates
          km = keyAt m;
        in
          if km < key then search key (m + 1) hi
          else if km == key then valueAt m
          else search key lo m;
  in
  assert (builtins.substring 0 4 raw) == "NKB1";
  let
    get = key: search key 0 n;   # value or null
  in
  {
    get = get;
    getOr = key: default:
      let v = get key;
      in if v == null then default else v;
    has = key: get key != null;
    count = n;
  }
"""


def main():
    src = TEMPLATE.replace("__B2__", b2_table())
    with open("kv_bin.nix", "w") as f:
        f.write(src)
    print(f"wrote kv_bin.nix: {len(src)} bytes, 255 table entries")


if __name__ == "__main__":
    main()